name:  test
on:  push
jobs:
  test:
    runs-on:  ubuntu-latest
    strategry:
　　　matrix:
        python-vertion:  ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses:  actions/checkout@v3
    - name:  All test
      run:  bash -xv ./test.bash
